### ISSUE TITLE
Use international English rather than US English by default

### ISSUE THREAD

**Issue by sammcj** [bttger/contributing-gen-web#41]
Really awesome tool!

In the interest of being inclusive and non-specific it would be nice if this project defaulted to using standard international English rather than US specific English.

If localisation is desired it could perhaps be provided via an option, (e.g. en (aka en-GB), en-US, es (aka es-ES), es-GT etc...).

**Comment by bttger** [comment]
Hey, using international english sounds like a good idea. Do you want to adapt the template? You can find it at https://github.com/bttger/contributing-gen

**Comment by sammcj** [comment]
Absolutely! I'll whip up a PR for it this week 😄

**Comment by sammcj** [comment]
Sorry became busy - https://github.com/bttger/contributing-gen/pull/6
